version: "3.8"

services:
  mongo:
    build: ./Dockerfiles/mongo/
    container_name: museum-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ~/mongo/data:/data/db
    ports:
      - 27017:27017
